version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/data/database.sqlite
      - ALLOWED_ORIGINS=http://localhost:5000
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - customer_network

  # Development services (use with docker-compose -f docker-compose.dev.yml up)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
      - /app/client/node_modules
    restart: unless-stopped
    networks:
      - customer_network
    profiles:
      - dev

volumes:
  app_data:
    driver: local

networks:
  customer_network:
    driver: bridge
