version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - customer_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - customer_network
    depends_on:
      - server

networks:
  customer_network:
    driver: bridge
